version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/instat_surveys
      - DEBUG_MODE=true
      - SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./generated:/app/generated
    networks:
      - instat-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=instat_surveys
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - instat-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - instat-network

  superset:
    image: apache/superset:latest
    environment:
      - SUPERSET_SECRET_KEY=your-superset-secret-key
    ports:
      - "8088:8088"
    networks:
      - instat-network

volumes:
  postgres_data:

networks:
  instat-network:
    driver: bridge
